sudo: false

os:
  - linux

language:
  - cpp

services:
  - docker

env:
  - DEPENDENCY_PACKAGES="libglib2.0-dev libgranite-dev libgtk-3-dev libgee-0.8-dev meson valac"

before_install:
  - docker pull YOUR/REPO:yakkety

script:
  - docker pull elementary/docker:loki
  - docker run -v "$PWD":/tmp/build-dir elementary/docker:loki /bin/sh -c "apt-get update && apt-get -y install $DEPENDENCY_PACKAGES && cd /tmp/build-dir && meson build --prefix=/usr && cd build && ninja"
